[target.wasm32-unknown-unknown]
rustflags = [
  # Optimize for size
  "-C", "opt-level=s",
  
  # Strip debug info
  "-C", "debuginfo=0",
  
  # Use 1 codegen unit for better optimizations
  "-C", "codegen-units=1"
]

[build]
# Deshabilitar LTO para WebAssembly
rustflags = ["-C", "embed-bitcode=no"]

[profile.release]
# Optimize for size
opt-level = 'z'  # Optimize for size
lto = true       # Enable Link Time Optimization
codegen-units = 1  # Better optimizations by compiling the crate as a single unit
panic = 'abort'   # Reduce size by using abort on panic
strip = true      # Strip symbols from binary (reduces size)
